const QUIZ_TYPES = {
  pictures: 'pictures',
  artists: 'artists',
}

const QUIZ_QUESTIONS_COUNT = 10
const QUIZ_IMAGES_ALL = 40
const QUIZ_ANSWERS_COUNT = 4
const IMAGES_ALL_COUNT = 239
const TIME_FOR_BLITZ = 30

export { QUIZ_TYPES, QUIZ_QUESTIONS_COUNT, QUIZ_IMAGES_ALL, QUIZ_ANSWERS_COUNT, IMAGES_ALL_COUNT, TIME_FOR_BLITZ }
